# Generated by Django 5.1.7 on 2025-03-26 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_servicio_options_alter_tiendaservicio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soporte',
            options={'ordering': ['-fecha_creacion']},
        ),
        migrations.RenameField(
            model_name='soporte',
            old_name='fecha_envio',
            new_name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='tienda',
        ),
        migrations.AddField(
            model_name='pago',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendent'), ('completado', 'Completat'), ('cancelado', 'Cancel·lat')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pago',
            name='tienda_servicio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.tiendaservicio'),
        ),
        migrations.AddField(
            model_name='soporte',
            name='asunto',
            field=models.CharField(default='Consulta', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='soporte',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendent'), ('en_proceso', 'En procés'), ('resuelto', 'Resolt')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='soporte',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='soporte',
            name='respuesta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo_pago',
            field=models.CharField(max_length=50),
        ),
    ]
