# Generated by Django 5.1.7 on 2025-03-23 15:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_solicitud_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servei', 'verbose_name_plural': 'Serveis'},
        ),
        migrations.AlterModelOptions(
            name='tiendaservicio',
            options={'verbose_name': 'Servei contractat', 'verbose_name_plural': 'Serveis contractats'},
        ),
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Actiu'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripció'),
        ),
        migrations.AddField(
            model_name='tiendaservicio',
            name='fecha_contratacion',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de contractació'),
        ),
        migrations.AddField(
            model_name='tiendaservicio',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notes de progrés'),
        ),
        migrations.AddField(
            model_name='tiendaservicio',
            name='precio_final',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Pot variar del preu base segons personalitzacions', max_digits=10, null=True, verbose_name='Preu final'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preu base'),
        ),
        migrations.AlterField(
            model_name='tiendaservicio',
            name='estado',
            field=models.CharField(choices=[('pendiente', "Pendent d'iniciar"), ('en_proceso', 'En procés'), ('completado', 'Completat'), ('pausado', 'Pausat')], default='pendiente', max_length=50, verbose_name='Estat'),
        ),
        migrations.AlterField(
            model_name='tiendaservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='Servei'),
        ),
        migrations.AlterField(
            model_name='tiendaservicio',
            name='tienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='core.tienda', verbose_name='Botiga'),
        ),
        migrations.AlterUniqueTogether(
            name='tiendaservicio',
            unique_together={('tienda', 'servicio')},
        ),
    ]
